[project]
name = "assys-montagehelfer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "board>=1.0",
    "flask>=3.1.0",
    "matplotlib>=3.10.1",
    "rpi-ws281x>=5.0.0",
]
